#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lzumanagement?serverTimezone=UTC&useSSL=false&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lzumanagement
    password: 159258jb
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 25
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  #指定国际化配置文件夹
  messages:
    basename: i18n.tx_messages
  #邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 694380623@qq.com #QQ邮箱
    password: zdplzphfcfgxbfci #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: aaa #可以任意
    properties.mail.display.sendname: bbb #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
#文件上传路径和服务器地址
file:
  absolutePath: /www/server/lzumanagement/vueServer/dist/img/
  uploadIP: http://121.36.32.198:8080/img/
#mybatis的配置
mybatis:
  #不应该和configuration同时存在
  #config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath:boot.dao.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: boot.bean
server:
  port: 8090
#网络请求配置
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
#pageHelper配置（官网推荐配置）
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 配置日志
logging:
  level:
    root: info
  file:
    path: logs
